"""
Generate lp13_data.h from lp13_problems.build_problems().

Emits, for each of the 13 problems, the constraint matrices in stacked dense
form K = [G; A] (m x n row-major) and q = [h; b] (length m), plus the variable
vectors c / l / u and the expected-status / expected-solution metadata. Dense
path is used for all 13 (matching torch pdlp.py, which is dense); the C harness
additionally builds the SPARSE view from the same K for dual-path consistency.

Unbounded bounds (float('inf')) are emitted as the C INFINITY macro.
"""

import math
import os

from lp13_problems import build_problems

HEADER = """\
/* AUTO-GENERATED by gen_lp13_header.py -- do not edit by hand.
 * 13 LP problems transcribed verbatim from tests/test_pdlp.py,
 * consumed by test_lp_solve13.c (C port) and oracle_lp_solve13.py (torch). */
#ifndef _LP13_DATA_H_
#define _LP13_DATA_H_

#include <stddef.h>
#include <math.h>   /* INFINITY for unbounded bounds */



typedef struct {
    const char *name;
    int n, m1, m2, m;          /* m = m1 + m2 */
    const double *G;           /* m1 * n */
    const double *h;           /* m1 */
    const double *A;           /* m2 * n */
    const double *b;           /* m2 */
    const double *c;           /* n */
    const double *l;           /* n */
    const double *u;           /* n */
    int exp_optimal, exp_primal_inf, exp_dual_inf, exp_iter_limit;
    const double *exp_x;       /* n, or NULL */
    double x_tol, obj_tol;
} lp13_problem_t;

extern const lp13_problem_t LP13_TABLE[13];
extern const int LP13_N;

#endif /* _LP13_DATA_H_ */
"""


def fmt_double(value):
    if isinstance(value, float) and math.isinf(value):
        return "INFINITY" if value > 0 else "-INFINITY"
    return repr(float(value))


def fmt_array(name, values):
    if len(values) == 0:
        return f"static const double {name}[1] = {{0.0}};\n"
    body = ", ".join(fmt_double(v) for v in values)
    return f"static const double {name}[{len(values)}] = {{ {body} }};\n"


def main():
    problems = build_problems()
    assert len(problems) == 13, f"expected 13 problems, got {len(problems)}"

    out_parts = [HEADER, "\n"]

    # fallback for zero-size matrices / vectors
    out_parts.append("static const double LP13_EMPTY[1] = {0.0};\n\n")

    body = []
    table_rows = []

    for idx, p in enumerate(problems):
        n = p["n"]
        m1 = p["m1"]
        m2 = p["m2"]
        m = m1 + m2

        # flatten stacked K = [G; A] (row-major)
        # torch 2D tensors .tolist() are nested lists -> flatten to 1D first
        G_flat = [v for row in p["G"] for v in row] if p["G"] else []
        A_flat = [v for row in p["A"] for v in row] if p["A"] else []
        K = []
        for r in range(m1):
            K.extend(G_flat[r * n:(r + 1) * n])
        for r in range(m2):
            K.extend(A_flat[r * n:(r + 1) * n])
        h_flat = p["h"]
        b_flat = p["b"]
        q = list(h_flat) + list(b_flat)

        g_name = f"p13_{idx}_G"
        h_name = f"p13_{idx}_h"
        a_name = f"p13_{idx}_A"
        b_name = f"p13_{idx}_b"
        c_name = f"p13_{idx}_c"
        l_name = f"p13_{idx}_l"
        u_name = f"p13_{idx}_u"
        x_name = f"p13_{idx}_x"

        # zero-size matrices / vectors point at the shared empty fallback
        g_ptr = g_name if m1 > 0 else "LP13_EMPTY"
        h_ptr = h_name if m1 > 0 else "LP13_EMPTY"
        a_ptr = a_name if m2 > 0 else "LP13_EMPTY"
        b_ptr = b_name if m2 > 0 else "LP13_EMPTY"
        c_ptr = c_name if n > 0 else "LP13_EMPTY"
        l_ptr = l_name if n > 0 else "LP13_EMPTY"
        u_ptr = u_name if n > 0 else "LP13_EMPTY"

        if m1 > 0:
            body.append(fmt_array(g_name, K[:m1 * n]))
            body.append(fmt_array(h_name, p["h"]))
        if m2 > 0:
            body.append(fmt_array(a_name, K[m1 * n:]))
            body.append(fmt_array(b_name, p["b"]))
        if n > 0:
            body.append(fmt_array(c_name, p["c"]))
            body.append(fmt_array(l_name, p["l"]))
            body.append(fmt_array(u_name, p["u"]))

        if p["exp_x"] is not None:
            body.append(fmt_array(x_name, p["exp_x"]))
            x_ptr = x_name
        else:
            x_ptr = "NULL"

        exp_opt = 1 if 0 in p["exp_status"] else 0
        exp_pin = 1 if 1 in p["exp_status"] else 0
        exp_din = 1 if 2 in p["exp_status"] else 0
        exp_itl = 1 if 3 in p["exp_status"] else 0

        body.append("")  # spacer
        table_rows.append(
            "    { \"%s\", %d, %d, %d, %d, %s, %s, %s, %s, %s, %s, %s, "
            "%d, %d, %d, %d, %s, %.6g, %.6g },"
            % (p["name"], n, m1, m2, m, g_ptr, h_ptr, a_ptr, b_ptr,
               c_ptr, l_ptr, u_ptr, exp_opt, exp_pin, exp_din, exp_itl,
               x_ptr, p["x_tol"], p["obj_tol"])
        )

    out_parts.append("\n".join(body))
    out_parts.append("\n\nconst lp13_problem_t LP13_TABLE[13] = {\n")
    out_parts.append("\n".join(table_rows))
    out_parts.append("\n};\n\n")
    out_parts.append("const int LP13_N = 13;\n")

    here = os.path.dirname(os.path.abspath(__file__))
    out_path = os.path.join(here, "lp13_data.h")
    with open(out_path, "w") as fh:
        fh.write("".join(out_parts))
    print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
